### ISSUE TITLE
Auditlog is not implemented

### ISSUE THREAD

**Issue by moonbse** [corazawaf/coraza-playground#42]
I have been trying to test some seclang rule but I am getting not implemented in audit log without any response

putting 

```
SecRule REQUEST_HEADERS:X-User-ID "@pm user123 user456" \
    "id:1002,phase:2,pass,log,msg:'User authorized',chain"
    SecRule REQUEST_URI "@streq /protected-endpoint" "t:none"

SecRule REQUEST_HEADERS:X-User-ID "!@pm user123 user456" \
    "id:1003,phase:2,deny,status:403,log,msg:'Unauthorized user',chain"
    SecRule REQUEST_URI "@streq /protected-endpoint" "t:none"
```

in directive

and then in request

```
curl -H "X-User-ID: user789" -X GET http://localhost:8080/api/hello
```

<img width="1728" alt="Screenshot 2024-12-19 at 4 58 04 PM" src="https://github.com/user-attachments/assets/867b6eb3-76f0-4094-98f8-9ef7e8b82fdf" />

I make sure that api/hello is running, also tried with a deployed URL but it seems like requests are not going anywhere

What will be the best way to test it as reverse proxy with custom seclang rules

With docker I can probably use something like :

```
https://github.com/jcchavezs/coraza-http-wasm-traefik
```

**Comment by fzipi** [comment]
Duplicate #20.
